# Netlify configuration for Gabriele Tanzi's Data-Driven Blog
[build]
  command = "echo 'Blog ready for deployment'"
  publish = "."

# Custom domain configuration
[context.production]
  command = "echo 'Production build for tanzitech.com'"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Author = "Gabriele Tanzi"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    Content-Security-Policy = "default-src 'self' 'unsafe-inline' data: https:; img-src 'self' data: https:; font-src 'self' data: https:;"

# Redirect rules
[[redirects]]
  from = "http://tanzitech.com/*"
  to = "https://tanzitech.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.tanzitech.com/*"
  to = "https://tanzitech.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "https://www.tanzitech.com/*"
  to = "https://tanzitech.com/:splat"
  status = 301
  force = true
