name: Deploy Blog Posts on Schedule

on:
  schedule:
    # Deploy every Monday at 9:00 AM UTC (adjust timezone as needed)
    - cron: '0 9 * * 1'
    # Deploy every Wednesday at 9:00 AM UTC
    - cron: '0 9 * * 3'
    # Deploy every Friday at 9:00 AM UTC
    - cron: '0 9 * * 5'
  
  # Allow manual triggering
  workflow_dispatch:
    inputs:
      post_date:
        description: 'Post date (YYYY-MM-DD)'
        required: true
        default: '2025-08-26'

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        
    - name: Get current date
      id: date
      run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      
    - name: Run deployment preparation
      run: node deploy-schedule.js
        
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./
        publish_branch: gh-pages
        
    - name: Create deployment summary
      run: |
        echo "## 🚀 Blog Deployment Summary" >> $GITHUB_STEP_SUMMARY
        echo "**Date:** ${{ steps.date.outputs.date }}" >> $GITHUB_STEP_SUMMARY
        echo "**Status:** ✅ Successfully deployed" >> $GITHUB_STEP_SUMMARY
        
        # Count posts by language
        EN_POSTS=$(find en/posts/ -name "*.html" 2>/dev/null | wc -l || echo "0")
        IT_POSTS=$(find it/posts/ -name "*.html" 2>/dev/null | wc -l || echo "0")
        DE_POSTS=$(find de/posts/ -name "*.html" 2>/dev/null | wc -l || echo "0")
        TOTAL_POSTS=$((EN_POSTS + IT_POSTS + DE_POSTS))
        
        echo "**Posts Available:**" >> $GITHUB_STEP_SUMMARY
        echo "- English: $EN_POSTS posts" >> $GITHUB_STEP_SUMMARY
        echo "- Italian: $IT_POSTS posts" >> $GITHUB_STEP_SUMMARY
        echo "- German: $DE_POSTS posts" >> $GITHUB_STEP_SUMMARY
        echo "- **Total: $TOTAL_POSTS posts**" >> $GITHUB_STEP_SUMMARY
